In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import UpSampling2D

Using TensorFlow backend.


In [2]:
X = np.asarray([
    [1, 2],
    [3, 4]    
])

print(X)

[[1 2]
 [3 4]]


In [6]:
X = X.reshape((1, 2, 2, 1))

print(X)

[[[[1]
   [2]]

  [[3]
   [4]]]]


In [7]:
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [8]:
yhat = model.predict(X)

print(yhat)

[[[[1.]
   [1.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [4.]
   [4.]]]]


In [9]:
yhat = yhat.reshape((4, 4))

print(yhat)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


<hr>

In [10]:
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1), size=(2, 3)))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_2 (UpSampling2 (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [11]:
yhat = model.predict(X)

print(yhat)

[[[[1.]
   [1.]
   [1.]
   [2.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [1.]
   [2.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [3.]
   [4.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [3.]
   [4.]
   [4.]
   [4.]]]]


In [13]:
yhat = yhat.reshape((4, 6))

print(yhat)

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]]


<hr>

In [14]:
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1), interpolation='bilinear'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_3 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [15]:
yhat = model.predict(X)

print(yhat)

[[[[1. ]
   [1.5]
   [2. ]
   [2. ]]

  [[2. ]
   [2.5]
   [3. ]
   [3. ]]

  [[3. ]
   [3.5]
   [4. ]
   [4. ]]

  [[3. ]
   [3.5]
   [4. ]
   [4. ]]]]


In [16]:
yhat = yhat.reshape((4, 4))

print(yhat)

[[1.  1.5 2.  2. ]
 [2.  2.5 3.  3. ]
 [3.  3.5 4.  4. ]
 [3.  3.5 4.  4. ]]
